### ISSUE TITLE
windows 11 installment

### ISSUE THREAD

**Issue by plankkim** [chasebank87/fabric-connector#9]
its probably a careless mistake but i really cant manage to install the fabric connector at windows. python is 3.7. fabric is installed. the plugin enabled, but when i run the connector.exe file a terminal window opens for a half second and nothing happens...

**Comment by chasebank87** [comment]
There is an app in the system tray, looks like a brain.Sent from my iPhoneOn Sep 20, 2024, at 7:32 AM, plankkim ***@***.***> wrote:﻿
its probably a careless mistake but i really cant manage to install the fabric connector at windows. python is 3.7. fabric is installed. the plugin enabled, but when i run the connector.exe file a terminal window opens for a half second and nothing happens...

**Comment by plankkim** [comment]
cant find a(my) brain icon and there is no app as fabric or connector or something similiar listed under installed apps

**Comment by chasebank87** [comment]
There is a bug on light mode, where the icon doesn't show. Can you check if there is an app with no icon in the system tray?

**Comment by plankkim** [comment]
unfortunately not...but i dont know how it would be there anyways without an icon. and at "all-apps" there is no programm listed with any of those names

**Comment by chasebank87** [comment]
It’s not an installed app, so it won’t be in start menu, and it has an icon but it doesn’t show on light backgrounds (the bug I was talking about)If it’s not there then the app is crashing are you sure you downloaded the correct exe?Sent from my iPhoneOn Sep 20, 2024, at 8:04 AM, plankkim ***@***.***> wrote:﻿
unfortunately not...but i dont know how it would be there anyways without an icon. and at "all-apps" there is no programm listed with any of those names

**Comment by plankkim** [comment]
fabric-connector_arm64 exe 
looks like its crashing...is there an older version i could use?

**Comment by oddstan** [comment]
compiled version for windows as well as compilation in windows are nt working. if i get it right it uses macos libraries, possible to install manually but fails when uses em during compilation
last compiled windows version that is working is 1.0.1.
though error is in apiauth
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "windows_app.py", line 9, in <module>
    from api import start_api_server, stop_api_server, API_KEY
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "api.py", line 40, in <module>
    API_KEY = generate_api_key()
  File "api.py", line 36, in generate_api_key
    hardware_uuid = get_hardware_uuid()
  File "api.py", line 30, in get_hardware_uuid
    result = subprocess.run(["wmic", "csproduct", "get", "UUID"], capture_output=True, text=True)
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1436, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
